version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Installing dependencies for validation..."
      - pip install -r requirements.txt
      - echo "Build phase complete."
artifacts:
  files:
    - '**/*'